# Generated by Django 4.0 on 2021-12-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
