# Generated by Django 4.0 on 2021-12-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_signup',
            field=models.BooleanField(default=False),
        ),
    ]
