# Generated by Django 4.0 on 2021-12-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_completed_signup'),
        ('trade', '0002_remove_stock_position_stock_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offer',
            new_name='Buy',
        ),
        migrations.RenameModel(
            old_name='Trade',
            new_name='Sell',
        ),
    ]
