# Generated by Django 4.0 on 2021-12-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_rename_offer_buy_rename_trade_sell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='trade',
            new_name='sell',
        ),
    ]
