# Generated by Django 4.0 on 2021-12-15 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_rename_trade_buy_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.stock'),
        ),
    ]
