# Generated by Django 4.0 on 2021-12-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_alter_buy_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='buy',
            name='stock',
        ),
        migrations.AddField(
            model_name='buy',
            name='stock',
            field=models.ManyToManyField(blank=True, to='trade.Stock'),
        ),
    ]
