# Generated by Django 4.0 on 2021-12-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_stock_last_updated_remove_buy_stock_buy_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='stock',
            field=models.ManyToManyField(blank=True, null=True, to='trade.Stock'),
        ),
    ]
